### ISSUE TITLE
Problem with utf-8

### ISSUE THREAD

**Issue by Nicat** [tburch/jsonblob#17]
I gets ugly view w/ UTF-8

[https://jsonblob.com/38c14aaf-d90e-11e6-b16a-595ca7566d52](example)

`{
  "data": "Hər şey yaxşı  olacağ"
}`

**Comment by tburch** [comment]
Looks like it's due to decoding the base64 encoded JSON that's on the page to render the HTML. I guess a better solution is to load the JSON blob via the API after the page has loaded, but I think there was a reason I didn't do that (maybe a limitation of the editor at that time - it was several years ago so I don't really remember).
`jsonlint.parse(decodeBase64("eyAgImRhdGEiOiAiSD8/ciA/P2V5IHlheD8/Pz8gb2xhY2E/PyJ9"));` Maybe using the snippet from http://stackoverflow.com/a/18519969/490888 instead of https://jsonblob.com/assets/js/base64.js would fix this? 

@Nicat Happy to review a PR if you want to do one.

**Comment by tburch** [comment]
I made a small [tweak](https://github.com/tburch/jsonblob/commit/6d81eada05f8689591b414a8b7420a468d128d64) to the server side base64 encoding/decoding helper to force UTF-8 and it looks better... but still not the same? It's written to disk as UTF-8, so I think that all should be working as expected.
```
{
  "data": "HÉr Åey yaxÅÄ± olacaÄ"
}
```

**Comment by tburch** [comment]
@Nicat Can you check to see if the UI now renders what you expect in your browser?

**Comment by Nicat** [comment]
@tburch I checked it. But the same result. 
https://jsonblob.com/f97333d4-f4ea-11e6-901d-c30ee4125ef3

**Comment by tburch** [comment]
@Nicat does this happen when using the UI or when using the API (or both)?

**Comment by tburch** [comment]
@Nicat I tested the following and it seems to work with the API:

Create the blob:
```curl -i -X "POST" -d '{"records":[{"description":"\u849c\u8089","id":282}]}' -H "Content-Type: application/json" -H "Accept: application/json" https://jsonblob.com/api/jsonBlob```

Get the blob: 
```curl -i -H "Content-Type: application/json" -H "Accept: application/json" https://jsonblob.com/api/jsonBlob/75661f47-f529-11e6-8161-53916555aa5c```

which returns 
```{"records":[{"description":"\u849c\u8089","id":282}]}```

The UI doesn't seem to render the unicode characters, so I guess I'll try to upgrade the editor I'm using (it just returns the string representation). https://jsonblob.com/75661f47-f529-11e6-8161-53916555aa5c

**Comment by Nicat** [comment]
Sure.  The problem w/ UI.

**Comment by tburch** [comment]
@Nicat It should be fixed now. https://jsonblob.com/332e0aec-f87b-11e6-8e23-c535786f2a03 seems to behave like I expect it to in the UI.
