### ISSUE TITLE
Error: Unrecognized field at: mongo

### ISSUE THREAD

**Issue by acsakshay** [tburch/jsonblob#21]
Hi, 

**Build with maven(mvn clean package) was successful**.

**Environment:**
OS: Ubuntu Server 16.04 LTS
Java: 1.8.0_144
Maven: Apache Maven 3.3.9
MongoDB: 3.4

I am new to java and maven and have less knowledge of how it works. While trying to start the application I got below error:

admin@localhost:~/jsonblob$ java -Ddw.mongo.type=uri -Ddw.mongo.uri=mongodb://127.0.0.1:27017/jsonblob -jar target/jsonblob.jar server target/config/jsonblob.yml

target/config/jsonblob.yml has an error:
  * Unrecognized field at: mongo
    Did you mean?:
      - ga
      - logging
      - server
      - metrics
      - blobManager
        [1 more]

Can you please explain or guide me on how to resolve this issue?

**Comment by tburch** [comment]
Sorry! I should update the `Readme`... there have been some big changes since I wrote that. Jsonblob doesn't use Mongo anymore. Instead it stores blobs on the file system. To run the app, here's what you need to do:

1. Run `mvn clean package` to build the jar
1. Run `java -Ddw.blobManager.fileSystemBlogDataDirectory=<PATH TO STORE BLOBS ON THE FILESYSTEM> -jar target/jsonblob.jar server target/config/jsonblob.yml`

That should be all you need. Good luck!
